[build.environment]
  NODE_VERSION = "18.17.0"

[[redirects]]
  from = '/_next/image/*'
  query = { q = ':quality', url = ':url', w = ':width' }
  to = '/.netlify/images?url=:url&w=:width&q=:quality'
  status = 200
  force = true

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }
  
[build.cache]
  paths = [
    ".next/cache",
    "node_modules/.cache"
  ]

[[headers]]
  for = "/api/optimize-image"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    ETag = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
