[build.environment]
  NODE_VERSION = "18.18.0"

[[redirects]]
  from = '/_next/image/*'
  query = { q = ':quality', url = ':url', w = ':width' }
  to = '/.netlify/images?url=:url&w=:width&q=:quality&resize=true'
  status = 200
  force = true

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }
  
[build.cache]
  paths = [
    ".next/cache",
    "node_modules/.cache"
  ]

[[headers]]
for = "/*"
[headers.values]
  Referrer-Policy = "no-referrer"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none';"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/_next/image/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
