name: CI Pipeline for Next.js Portfolio

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm ci  # Install project dependencies (including dev dependencies)

      - name: Lint the code
        run: |
          npm run lint  # Run linting to catch potential issues

      - name: Run Jest tests
        run: |
          npx jest

      - name: Build the project
        run: |
          npm run build  # Build the Next.js project
          
  lighthouse:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: "https://rileyhoffman.com"
          uploadArtifacts: true
          temporaryPublicStorage: true
          budgetPath: "./lighthouse-budget.json"